name: Run Module Tests

on:
  push:
    branches:
      - develop
      - 'feature*'
      - 'release/**'
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - develop
      - 'feature*'
      - 'release/**'

jobs:
  run-tests:
    uses: openimis/openimis-fe_js/.github/workflows/ci-module.yml@develop
    with:
      module-path: ./current-module
      repo: ${{ github.repository }}
