name: Run Module Tests

on:
  push:
    branches: [develop, feature*, release*]
  pull_request:
    branches: [develop, feature*, release*]

jobs:
  run-tests:
    uses: openimis/openimis-fe_js/.github/workflows/test-module.yml@develop
    with:
      module-path: .
